# Password Generator

## Overview

Welcome to my Password Generator repository! On Day 5 of my 100 Days of Code challenge, I created a password generator that generates two types of passwords based on the user's input - a sequential password and a shuffled password, to ensure maximum security.

## Project Description

The password generator allows the user to specify the desired number of letters, symbols, and numbers they want in the password. Using this input, the generator creates two types of passwords:

1. Sequential Password: The password is generated following a sequence where it starts with letters and then includes numbers. For example, "abc123".

2. Shuffled Password: The password is generated by shuffling the sequence of characters to remove any specific patterns, ensuring better security. For example, "a1b2c3".

## Learning Highlights

During the implementation of this project, I focused on the fundamentals of for loops and discovered the following key learning points:

- Understanding for loops and using them to iterate over a range of values using the `range()` function (for x in range(start, end, step/gap)).
- Learning about random shuffling in Python and how to shuffle a list using the `random.shuffle()` function.
- Converting a list of characters into a string to create the shuffled password.
- Gaining insights into the logic behind for loops and practicing algorithmic thinking for password generation.

## How to Use the Password Generator

To use the password generator, follow these steps:

1. Clone or download this repository to your local machine.
2. Open the Python script `main.py` in your preferred Python IDE or text editor.
3. Run the script, and the generator will prompt you to enter the number of letters, symbols, and numbers you want in the password.
4. The generator will create both a sequential and a shuffled password based on your input.

Feel free to customize the password generator further and experiment with different password lengths and combinations.

## Project Insights

Building the password generator required a solid understanding of for loops and the logic behind password generation. It was challenging to implement the shuffling logic using lists and then converting the list back to a string for the shuffled password.

## Next Steps

I plan to enhance the password generator by adding more options for password complexity, such as including uppercase letters, special characters, or customizable password lengths. Additionally, I will continue practicing algorithmic thinking and exploring more Python functionalities to improve the generator's efficiency and security.

## Acknowledgments

I am thankful for the coding resources and tutorials that have contributed to my understanding of for loops and password generation. Special thanks to the "100 Days of Code" challenge for keeping me engaged and committed to my coding journey.

---
Note: Customize this README file further to add any specific details about the password generator's features, the implementation of the shuffling logic, or any challenges you encountered during development. Additionally, you may include examples of generated passwords for reference.
